# Project Information
site_name: Senior Wiki
site_description: Senior Wiki
site_author: Terrasse
site_url: https://Jerry-Terrasse.github.io/senior-wiki

# Repository
repo_name: 'Jerry-Terrasse/senior-wiki'
repo_url: 'https://github.com/Jerry-Terrasse/senior-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Terrasse'

# Folders
docs_dir: source
site_dir: docs

# Contents
nav:
  - 简介: index.md
  - 化学:
    - 化学实验基本方法: Chemistry/exp-mtd.md
  - 生物:
    - 细胞:
      - 细胞与生物圈: Biology/cell.md
      - 细胞的多样性与统一性: Biology/cell-d-u.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
    logo: 'material/school'
  features:
    - tabs
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Customization
extra:
  search:
    language: 'zh'
  # disqus: 'ctf-wiki'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
    - '_static/js/extra.js'
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
    - '_static/css/extra.css'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false 
    - def_list 
    - footnotes 
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
